apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hadoop-deploy
  name: hadoop-deploy
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hadoop-deploy
  template:
    metadata:
      labels:
        app: hadoop-deploy
    spec:
      containers:
      - name: hadoop
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
            
