apiVersion: v1
kind: Service
metadata:
  labels:
    app: hadoop-svc
  name: hadoop-svc
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: hadoop-svc
  type: {{ .Values.service.type }}
